
    name: prod-staticwebApp
    on:
      workflow_dispatch:
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Build And Deploy
            uses: Azure/static-web-apps-deploy@v1
            with:
              azure_static_web_apps_api_token: "069b61352c0bdd7eb35957dde5467665209ec56f5cd7aa937e02a3315689b53d1-607c59e5-0889-41a9-9572-cb116c4d3f0500f30788"

              action: 'upload'
              app_location: '/'
              output_location: 'dist'
              app_build_command: 'npm run webApp'
    