
    name: prod-staticwebApp
    on:
      workflow_dispatch:
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Build And Deploy
            uses: Azure/static-web-apps-deploy@v1
            with:
              azure_static_web_apps_api_token: "d943d5c9418488e5514e1845731f45719d42e23460849365bf726cd0871c573d1-bf11f459-3b79-4148-99b1-ee189140b5f401072470"

              action: 'upload'
              app_location: '/'
              output_location: 'dist'
              app_build_command: 'npm run webApp'
    