
    name: prod-staticwebApp
    on:
      workflow_dispatch:
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Build And Deploy
            uses: Azure/static-web-apps-deploy@v1
            with:
              azure_static_web_apps_api_token: "303fc0c6fe88cbdb967e450012456039eb103406a25a4eeed79395442a47d3a51-18b7ba08-7a13-4707-9ece-1d5ac899448e00f28285"

              action: 'upload'
              app_location: '/'
              output_location: 'dist'
              app_build_command: 'npm run webApp'
    