
    name: prod-staticwebApp
    on:
      workflow_dispatch:
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Build And Deploy
            uses: Azure/static-web-apps-deploy@v1
            with:
              azure_static_web_apps_api_token: "03fd969d0c966404b71f43a2007fada6503c4e538966317227951a28c9bf8ce41-f0534dab-d0ef-4b30-b398-3a7eefeb6ca100f33174"
              action: 'upload'
              app_location: '/'
              output_location: 'dist'
              app_build_command: 'npm run webApp'
    
