
    name: prod-staticwebApp
    on:
      workflow_dispatch:
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Build And Deploy
            uses: Azure/static-web-apps-deploy@v1
            with:
              azure_static_web_apps_api_token: "bb68fe5c13b0cb9cf9a58806f342e1d1e3c845b6d66f263054ee2b5b89db79d71-9eb07f76-df3b-45ac-ab7b-a8ed93697fe001072451"

              action: 'upload'
              app_location: '/'
              output_location: 'dist'
              app_build_command: 'npm run webApp'
    